name: shlink_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.9.1+5

environment:
  sdk: ^2.19.0
dependencies:
  flutter:
    sdk: flutter

  #
  # RUN THE FOLLOWING COMMANDS AFTER EVERY PUB-GET
  # $ flutter packages pub run license_generator check
  # $ flutter packages pub run license_generator generate
  #

  cupertino_icons: ^1.0.5
  http: ^0.13.6
  flutter_process_text: ^1.1.2
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  qr_flutter: ^4.1.0
  tuple: ^2.0.2
  intl: ^0.18.1
  dynamic_color: ^1.6.6
  url_launcher: 6.1.9
  package_info_plus: ^4.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  license_generator: ^1.0.5
  flutter_launcher_icons:
    git:
        url: https://github.com/OutdatedGuy/flutter_launcher_icons.git
        ref: feat/monochrome-icons-support

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon_monochrome.png"